### ISSUE TITLE
Ajax error: bad post signature with Chromium

### ISSUE THREAD

**Issue by ghost** [miguelfreitas/twister-core#146]
Hi I just created two twister accounts @sploing and @sploinga and I can't post with any of them on Chromium. This works with FF. My twister version is the latest one, meaning that I downloaded and compiled it on this morning. Also, I am using Chromium version 32.0.1700.102 Ubuntu 13.10 (32.0.1700.102-0ubuntu0.13.10.1~20140128.970.1).

Any hints ?

**Comment by P3lUZa** [comment]
I have the same problem with both Chromium and Firefox (no addons)

**Comment by P3lUZa** [comment]
Now I can :dancers: Yep, its a wrong message, it should say "Wait till your name is diistributed"

**Comment by d47081** [comment]
The same issue with attempts to RT some twists

I don't know how to properly fix it on the registration step,
but, have updated alert messages in the twisterarmy fork, because current messages may really confuse new users to close the app definitively.

https://github.com/twisterarmy/twister-core/commit/c1b0d4e993f573c0608cba9f1a34cf82cfa65cb6
