### ISSUE TITLE
API is a mess

### ISSUE THREAD

**Issue by Tschaul** [miguelfreitas/twister-core#322]
I started doing some experiments at http://github.com/Tschaul/LibTwister for a reusable low level twister library in javascript. I keep running into problems implementing the current API in a clean way. As far as i understand, the torrents system should provide a more efficient system of post distribution, than repeated DHT lookups. I understand that this significantly decreases the network load. But why are there different API calls necessary to access a post through one or the other? Couldn't twisterd just check if it has joined a given swarm and do the DHT lookup if not?

I think when moving towards the client side crypto it makes more sense to have a lean API with little other than dhtget and dhtput.

**Comment by Tschaul** [comment]
Just found [here](https://github.com/miguelfreitas/twister-core/blob/6115190f44d932e1ef1e3aaf4ad8030af7a3d4d4/src/bitcoinrpc.cpp#L198) that the torrent based methods are deactivated for public servers. So they are already "deprecated" somewhat?

**Comment by digital-dreamer** [comment]
No, they are not deprecated. “Public server” is a special mode where you open your instance to the whole world as a gateway into the Twister network to passively read messages without logging in. In this mode, only a subset of RPC methods is allowed for security reasons. It is still an experimental feature that is not used in the real world yet.

**Comment by miguelfreitas** [comment]
Public server (and the node.js proxy) may also work as a basis for the browser-crypto idea.

I understand the idea of abstracting out the difference of getting posts from DHT and torrents, and i'm partly fond of it. However there are important practical differences: post from torrent is mostly immediate while from DHT involves long timeouts. 

This is important for browsers since the number of simultaneous connections is limited to 5 or 6. If we use all the 6 connections for long waiting queries on DHT, the whole UI gets very unusable as the fast (local) requests are not processed (they would keep waiting on a queue for an available connection slot browser=>daemon).

**Comment by Tschaul** [comment]
I understand. It should still be doable somehow... i'll think about it

**Comment by Tschaul** [comment]
The last connection could be reserved as a fast lane with a low timeout parameter. If all other connections are in use, a request would first put on the fast lane. If it times out, it would get scheduled for the normal connections. twisterd could detect the low timeout parameter and don't even try the DHT lookup if the data is not available locally. Also, resources that are not in torrents could be banned from the fast lane. That should preserve the responsiveness and keep things more simple to implement.

Also, the functional restrictions of the browsers, in my opinion, should not add complexity for API consumers that are not effected by these restrictions (e.g. node.js, python or possibly native clients).

**Comment by Tschaul** [comment]
stupid idea, you are right.
