### ISSUE TITLE
storing private followings and blockend users in the dht

### ISSUE THREAD

**Issue by Tschaul** [miguelfreitas/twister-core#372]
In my client i want to store the private followings, blocked users and possibly other settings in the dht, so they can be synced between multiple browsers/clients. I just realised that twisterd does not restrict the dhtput and dhtget command to the standard resources.

These settings need to be encrypted of course, so i would suggest to use the exact same scheme of direct messages, simply encrypted for the pubkey of the user. The decrypted result would then have the same structure as the following resources, a list of usernames.

Im asking here because i don't know whether the protocol/api is actually allowing the use of arbitrary dht resources. Going by the rfc standard (https://www.ietf.org/rfc/rfc2119.txt) is it a MAY, SHOULD NOT or MUST NOT ?

**Comment by Tschaul** [comment]
Storing the latest read mentions and latest read direct message per following would also be cool. Then the highlighting of new messages could also be synced between clients.

**Comment by rodneyrod** [comment]
Couldn't this be done in an easier way? Couldn't these settings be shared between clients through a hidden group message instead of putting it all in the DHT? Sure, that'll mean that clients have to be online at the same time to sync info, but it could be done.

**Comment by Tschaul** [comment]
And when a new client imports the private key it first has to scan the complete torrent to find the invite, where the settings is the very first thing the client would need to set itself up. You already mention the problem that two clients need to be only for the syncing to work. 

Comparing to the load that mentions and hashtags put on the dht this should really be a minor thing.

Short: I don't see how this is easier.

Group messages in itself are a problem for lightweight e2e-crypto clients. The complete torrents don't fit into browser cache (~5MB), so they have to be prioritised. Also decrypting all messages since the beginning of the torrents just takes a long time during which the app/browser will go to sleep and just stop. As long as the client has not found that invite the user still appears to be part of the conversation but the messages don't reach him/her and there is no way the user can notice.

Maybe the message ids containing group invites should also be stored on the dht encryptedly :-) (maybe not, don't know)

**Comment by miguelfreitas** [comment]
@Tschaul the policy i've adopted in twister is to not explicitly forbid any unknown DHT resource, that is, we are not limited to known ones and new resources may be created to explore new possibilities - exactly what you are suggesting to sync private followings, blockings etc.

that said, while we don't forbid unknown resources, we don't prioritize them either. that means they are not prioritized for automatic refresh and may expire (became unavailable) before other (known) resources. the reason is to prevent spaming of unknown dht resources to win over what we currently consider important.

so what i'd suggest is: give it a try and put those dht resources you want. if we decide for the longer persistence of some of them, we may always change twisterd (of course it will require peers to upgrade their clients).

other possibility is storing into user's torrent. long time persistency is usually better, but startup sync'ing may take a little longer. another idea: we may even use existing standard dht resources (like profile) to store just the piece number of additional information to be retrieved from torrent.

**Comment by Tschaul** [comment]
Thanks for the clear answer. The autorefreshing probably only works for walletusers, right? If twisterd is run as public proxy the client needs to refresh them, or not?

**Comment by miguelfreitas** [comment]
The refresh of DHT items doesn't depend on walletusers. Whatever resources which have been dhtput in local node (as per remote requests), and that follow some set of rules, are automatically refreshed.

**Comment by Tschaul** [comment]
very handy
